# Generated by Django 5.2.8 on 2026-05-19 15:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('engine_type', models.CharField(max_length=200, null=True)),
                ('year_built', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1903)])),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('tach_current', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('hobbs_current', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('fleet_status', models.CharField(choices=[('active', 'Active'), ('maintenance_due', 'Maintenance Due'), ('aog', 'AOG'), ('grounded', 'Grounded')], default='active', max_length=40)),
                ('aircraft_type', models.CharField(blank=True, default='', max_length=60)),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('hobbs_time', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locations', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AircraftMaintenanceInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('interval_type', models.CharField(choices=[('hours', 'Hours'), ('days', 'Days'), ('both', 'Both')], default='hours', max_length=20)),
                ('due_every_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('due_every_days', models.PositiveIntegerField(blank=True, null=True)),
                ('last_done_tach', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('last_done_hobbs', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('last_done_date', models.DateField(blank=True, null=True)),
                ('is_ad', models.BooleanField(default=False)),
                ('ad_number', models.CharField(blank=True, default='', max_length=80)),
                ('ad_revision', models.CharField(blank=True, default='', max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_intervals', to='api.aircraft')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AircraftPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='aircraft_photos/')),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.aircraft')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='aircraft',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aircraft', to='api.company'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('company_role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('mechanic', 'Mechanic'), ('dispatcher', 'Dispatcher'), ('pilot', 'Pilot'), ('dispatcher', 'Dispatcher')], default='pilot', max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('employee_id', models.PositiveIntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.company')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reported', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('ata_code', models.CharField(blank=True, max_length=50)),
                ('tach_time', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='discrepancies_signatures/')),
                ('signature_date', models.DateField(blank=True, null=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='api.aircraft')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiscrepancyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated')], default='updated', max_length=32)),
                ('summary', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discrepancy_activities', to=settings.AUTH_USER_MODEL)),
                ('discrepancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.discrepancy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=250, null=True)),
                ('origin', models.CharField(max_length=250, null=True)),
                ('destination', models.CharField(max_length=250, null=True)),
                ('departure_time', models.DateTimeField(null=True)),
                ('arrival_time', models.DateTimeField(null=True)),
                ('route', models.CharField(blank=True, null=True)),
                ('flight_type', models.CharField(choices=[('training', 'Training'), ('charter', 'Charter'), ('positioning', 'Positioning'), ('maintenance ferry', 'Maintenance Ferry')], default='training', max_length=255)),
                ('pilot_requirement', models.CharField(choices=[('student', 'Student'), ('private', 'Private'), ('commercial', 'Commercial'), ('airline', 'Airline')], default='private', max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('approved', 'Approved'), ('pending approval', 'Pending Approval'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending approval', max_length=255)),
                ('aircraft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='api.aircraft')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='api.company')),
                ('dispatcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_dispatcher', to=settings.AUTH_USER_MODEL)),
                ('primary_pilot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_pilot', to=settings.AUTH_USER_MODEL)),
                ('secondary_pilot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_pilot', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_name', models.CharField(default='Main', max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AP_certificate_number', models.PositiveIntegerField(blank=True, null=True)),
                ('mechanic_certificate_img', models.ImageField(blank=True, null=True, upload_to='mechanic_cert/')),
                ('inspector_authentication', models.BooleanField(default=False)),
                ('authentication_img', models.ImageField(blank=True, null=True, upload_to='faa_auth/')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('stock_alert', models.PositiveIntegerField(default=0, help_text='Number where stock needs to be reordered')),
                ('stock_alert_percentage', models.FloatField(default=0.1, help_text='What percentile low stock warning shows up', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('shop_location', models.CharField(blank=True, max_length=100, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inventory')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.part')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='parts',
            field=models.ManyToManyField(blank=True, related_name='inventories', through='api.InventoryPart', to='api.part'),
        ),
        migrations.CreateModel(
            name='AircraftPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('expiration_hobbs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aircraft')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_aircrafts', to='api.part')),
            ],
        ),
        migrations.AddField(
            model_name='aircraft',
            name='aircraft_parts',
            field=models.ManyToManyField(blank=True, related_name='aircrafts', through='api.AircraftPart', to='api.part'),
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medically_cleared_until', models.DateField(blank=True, null=True)),
                ('pilot_certificate', models.CharField(choices=[('none', 'None'), ('student', 'Student'), ('private', 'Private'), ('commercial', 'Commercial'), ('airline', 'Airline')], default='none', max_length=255)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('serial_number', models.CharField(max_length=200)),
                ('calibration_due_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_date', models.DateField()),
                ('performed_by', models.CharField(max_length=200)),
                ('next_due_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_history', to='api.tool')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('awaiting_parts', 'Awaiting Parts'), ('closed', 'Closed')], default='open', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_by', models.DateField(blank=True, null=True)),
                ('tach_time', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('hobbs_time', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ATA_code', models.IntegerField(blank=True, null=True)),
                ('components_affected', models.CharField(blank=True, max_length=200)),
                ('components_image', models.ImageField(blank=True, null=True, upload_to='work_order_components/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='work_order_signatures/')),
                ('signature_date', models.DateField(blank=True, null=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='api.aircraft')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_work_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='discrepancy',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discrepancies', to='api.workorder'),
        ),
        migrations.CreateModel(
            name='WorkOrderActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated')], default='updated', max_length=32)),
                ('summary', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_activities', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.workorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('part_life', models.DecimalField(blank=True, decimal_places=2, help_text='Number of hobbs hours the part is good for. Optional, only used if part is tracked by hobbs time.', max_digits=15, null=True)),
                ('part_expiration_date', models.DateField(blank=True, help_text='Date the part expires. Optional, only used if part is tracked by expiration date.', null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.part')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.workorder')),
            ],
        ),
        migrations.AddField(
            model_name='workorder',
            name='parts_needed',
            field=models.ManyToManyField(blank=True, through='api.WorkOrderPart', to='api.part'),
        ),
    ]
