# Generated by Django 5.2.8 on 2025-11-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='medically_cleared_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
