# Generated by Django 5.2.8 on 2025-11-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile_medically_cleared_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Numbers only, do not add "(", ")" or "-" ', max_length=10, null=True),
        ),
    ]
