# Generated by Django 5.2.8 on 2025-11-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_profile_ap_certificate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='inspector_authentication',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_role',
            field=models.CharField(choices=[('owner', 'Owner'), ('mechanic', 'Mechanic'), ('pilot', 'Pilot'), ('manager', 'Manager')], default='pilot', max_length=255),
        ),
    ]
