# Generated by Django 5.2.7 on 2025-11-21 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_discrepancy_workorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='discrepancy',
        ),
        migrations.AddField(
            model_name='discrepancy',
            name='tach_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='discrepancy',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discrepancies', to='api.workorder'),
        ),
        migrations.AlterField(
            model_name='discrepancy',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
