# Generated by Django 5.2.8 on 2025-11-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_profile_ap_certificate_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mechanic_info',
            new_name='Mechanic',
        ),
        migrations.RenameModel(
            old_name='pilot_info',
            new_name='Pilot',
        ),
        migrations.AddField(
            model_name='company',
            name='locations',
            field=models.CharField(blank=True, null=True),
        ),
    ]
