# Generated by Django 5.2.8 on 2025-12-02 23:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_part_inspection_due_in_part_low_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='low_stock',
        ),
        migrations.AddField(
            model_name='part',
            name='stock_alert_percentage',
            field=models.FloatField(default=0.1, help_text='What percentile low stock warning shows up', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='part',
            name='aircraft',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.aircraft'),
        ),
    ]
