# Generated by Django 5.2.8 on 2025-12-02 23:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_part_low_stock_part_stock_alert_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='part',
            name='inspection_due_in',
        ),
        migrations.RemoveField(
            model_name='part',
            name='last_inspected',
        ),
        migrations.RemoveField(
            model_name='part',
            name='shop_location',
        ),
        migrations.RemoveField(
            model_name='part',
            name='stock_alert',
        ),
        migrations.RemoveField(
            model_name='part',
            name='stock_alert_percentage',
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_inspected', models.DateField(null=True)),
                ('inspection_due_in', models.PositiveIntegerField(blank=True, help_text='Days', null=True)),
                ('in_stock', models.PositiveIntegerField(default=0)),
                ('stock_alert', models.PositiveIntegerField(default=0, help_text='Number where stock needs to be reordered')),
                ('stock_alert_percentage', models.FloatField(default=0.1, help_text='What percentile low stock warning shows up', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('shop_location', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.part')),
            ],
        ),
    ]
