# Generated by Django 5.2.8 on 2025-12-11 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_flight_alter_inventory_company_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(null= True, on_delete=django.db.models.deletion.CASCADE, to='api.aircraft'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='company',
            field=models.ForeignKey(null= True, on_delete=django.db.models.deletion.CASCADE, to='api.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(null= True, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_type',
            field=models.CharField(choices=[('training', 'Training'), ('charter', 'Charter'), ('positioning', 'Positioning'), ('maintenance ferry', 'Maintenance Ferry')], default='pilot', max_length=255),
        ),
        migrations.AddField(
            model_name='flight',
            name='route',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
