# Generated by Django 5.2.8 on 2025-12-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_flight_aircraft_flight_company_flight_flight_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
