# Generated by Django 5.2.8 on 2025-12-16 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_flight_primary_pilot'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='secondary_pilot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_flights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flight',
            name='primary_pilot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_flights', to=settings.AUTH_USER_MODEL),
        ),
    ]
