# Generated by Django 5.2.8 on 2025-12-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_flight_secondary_pilot_alter_flight_primary_pilot'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
