# Generated by Django 5.2.8 on 2025-12-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_flight_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='pilot_requirement',
            field=models.CharField(choices=[('student', 'Student'), ('private', 'Private'), ('commercial', 'Commercial'), ('airline', 'Airline')], default='private', max_length=255),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_type',
            field=models.CharField(choices=[('training', 'Training'), ('charter', 'Charter'), ('positioning', 'Positioning'), ('maintenance ferry', 'Maintenance Ferry')], default='training', max_length=255),
        ),
    ]
