# Generated by Django 5.2.8 on 2026-02-18 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_workorder_discrepancy_discrepancy_tach_time_and_more'),
        ('api', '0024_flight_pilot_requirement_alter_flight_flight_type'),
    ]

    operations = [
    ]
