# Generated by Django 5.2.12 on 2026-03-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_flight_pilot_requirement_alter_flight_flight_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_role',
            field=models.CharField(
                choices=[
                    ('owner', 'Owner'),
                    ('manager', 'Manager'),
                    ('mechanic', 'Mechanic'),
                    ('pilot', 'Pilot'),
                    ('dispatcher', 'Dispatcher'),
                ],
                default='pilot',
                max_length=255,
            ),
        ),
    ]
