# Generated by Django 6.0.2 on 2026-02-21 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_flight_pilot_requirement_alter_flight_flight_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('awaiting_parts', 'Awaiting Parts'), ('closed', 'Closed')], default='open', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_by', models.DateField(blank=True, null=True)),
                ('tach_time', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('hobbs_time', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ATA_code', models.IntegerField(blank=True, null=True)),
                ('components_affected', models.CharField(blank=True, max_length=200)),
                ('components_image', models.ImageField(blank=True, null=True, upload_to='work_order_components/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='work_order_signatures/')),
                ('signature_date', models.DateField(blank=True, null=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='api.aircraft')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_work_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reported', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('ata_code', models.CharField(blank=True, max_length=50)),
                ('tach_time', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='api.aircraft')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discrepancies', to='api.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.part')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.workorder')),
            ],
        ),
        migrations.AddField(
            model_name='workorder',
            name='parts_needed',
            field=models.ManyToManyField(blank=True, through='api.WorkOrderPart', to='api.part'),
        ),
    ]
