# Generated by Django 5.2.12 on 2026-03-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_profile_company_role_workorder_discrepancy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='registration_number',
            field=models.CharField(max_length=50),
        ),
    ]
