# Generated by Django 5.2.8 on 2026-02-18 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_merge_20260218_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.part')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.workorder')),
            ],
        ),
        migrations.AddField(
            model_name='workorder',
            name='parts_needed',
            field=models.ManyToManyField(blank=True, through='api.WorkOrderPart', to='api.part'),
        ),
    ]
