# Generated by Django 5.2.8 on 2026-02-18 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_workorderpart_workorder_parts_needed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='completion_notes',
        ),
        migrations.AddField(
            model_name='workorder',
            name='ATA_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='components_affected',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='workorder',
            name='components_image',
            field=models.ImageField(blank=True, null=True, upload_to='work_order_components/'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='due_by',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='hobbs_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='work_order_signatures/'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='signature_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_work_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorder',
            name='tach_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
