# Generated by Django 5.2.8 on 2026-02-24 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_workorder_completion_notes_workorder_ata_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discrepancy',
            name='component_affected',
        ),
    ]
