# Generated by Django 5.2.8 on 2026-02-26 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_discrepancy_component_affected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='approved',
        ),
        migrations.AddField(
            model_name='flight',
            name='dispatcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_dispatcher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('approved', 'Approved'), ('pending approval', 'Pending Approval'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending approval', max_length=255),
        ),
        migrations.AlterField(
            model_name='flight',
            name='primary_pilot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_pilot', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flight',
            name='secondary_pilot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_pilot', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_role',
            field=models.CharField(choices=[('owner', 'Owner'), ('mechanic', 'Mechanic'), ('dispatcher', 'Dispatcher'), ('pilot', 'Pilot'), ('manager', 'Manager')], default='pilot', max_length=255),
        ),
    ]
