# Generated by Django 5.2.8 on 2026-02-28 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_flight_approved_flight_dispatcher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='api.aircraft'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='api.company'),
        ),
    ]
