# Generated by Django 5.2.8 on 2026-02-28 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_flight_aircraft_alter_flight_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aircraft', to='api.company'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.company'),
        ),
    ]
