# Generated by Django 5.2.8 on 2026-03-09 16:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_aircraft_company_alter_profile_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='inspection_due_in',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='last_inspected',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='shop_location',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='stock_alert',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='stock_alert_percentage',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='part',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='inventoryparts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('stock_alert', models.PositiveIntegerField(default=0, help_text='Number where stock needs to be reordered')),
                ('stock_alert_percentage', models.FloatField(default=0.1, help_text='What percentile low stock warning shows up', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('shop_location', models.CharField(blank=True, max_length=100, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inventory')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.part')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='part',
            field=models.ManyToManyField(blank=True, through='api.inventoryparts', to='api.part'),
        ),
    ]
