# Generated by Django 5.2.8 on 2026-03-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_inventory_in_stock_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='inventoryparts',
            new_name='InventoryPart',
        ),
    ]
