# Generated by Django 5.2.8 on 2026-03-09 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_rename_inventoryparts_inventorypart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='part',
            new_name='parts',
        ),
    ]
