# Generated by Django 5.2.8 on 2026-03-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_rename_part_inventory_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='parts',
            field=models.ManyToManyField(blank=True, related_name='inventories', through='api.InventoryPart', to='api.part'),
        ),
    ]
