# Generated by Django 5.2.8 on 2026-03-31 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_aircraft_registration_number'),
        ('api', '0036_alter_discrepancy_reporter'),
    ]

    operations = [
    ]
