# Generated by Django 5.2.8 on 2026-03-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_discrepancy_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='inventory_name',
            field=models.CharField(default='Main', max_length=100),
        ),
    ]
