# Generated by Django 5.2.12 on 2026-03-31 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_merge_20260331_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='pilot_certificate',
            field=models.CharField(choices=[('none', 'None'), ('student', 'Student'), ('private', 'Private'), ('commercial', 'Commercial'), ('airline', 'Airline')], default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('mechanic', 'Mechanic'), ('dispatcher', 'Dispatcher'), ('pilot', 'Pilot'), ('dispatcher', 'Dispatcher')], default='pilot', max_length=255),
        ),
    ]
