# Generated by Django 5.2.8 on 2026-03-31 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_merge_20260331_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='discrepancy',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='discrepancies_signatures/'),
        ),
        migrations.AddField(
            model_name='discrepancy',
            name='signature_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorder',
            name='completion_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='pilot_certificate',
            field=models.CharField(choices=[('none', 'None'), ('student', 'Student'), ('private', 'Private'), ('commercial', 'Commercial'), ('airline', 'Airline')], default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('mechanic', 'Mechanic'), ('dispatcher', 'Dispatcher'), ('pilot', 'Pilot'), ('dispatcher', 'Dispatcher')], default='pilot', max_length=255),
        ),
    ]
