# Generated by Django 5.2.8 on 2026-04-03 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_inventory_inventory_name'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "CREATE TABLE IF NOT EXISTS api_aircraftpart ("
                        "id bigserial PRIMARY KEY, "
                        "expiration_date date NULL, "
                        "expiration_hobbs numeric(15,2) NULL, "
                        "aircraft_id bigint NOT NULL REFERENCES api_aircraft(id) ON DELETE CASCADE, "
                        "part_id bigint NOT NULL REFERENCES api_part(id) ON DELETE CASCADE"
                        ");"
                    ),
                    reverse_sql="DROP TABLE IF EXISTS api_aircraftpart;",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='AircraftPart',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('expiration_date', models.DateField(blank=True, null=True)),
                        ('expiration_hobbs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                        ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aircraft')),
                        ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_aircrafts', to='api.part')),
                    ],
                ),
                migrations.AddField(
                    model_name='aircraft',
                    name='aircraft_parts',
                    field=models.ManyToManyField(blank=True, related_name='aircrafts', through='api.AircraftPart', to='api.part'),
                ),
            ],
        ),
    ]
