# Generated by Django 5.2.8 on 2026-04-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_aircraftpart_aircraft_aircraft_parts'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE api_aircraft ADD COLUMN IF NOT EXISTS hobbs_time numeric(15,2) DEFAULT 0 NOT NULL;",
                    reverse_sql="ALTER TABLE api_aircraft DROP COLUMN IF EXISTS hobbs_time;",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='aircraft',
                    name='hobbs_time',
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
            ],
        ),
    ]
