# Generated by Django 5.2.8 on 2026-04-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_aircraftpart_aircraft_aircraft_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='hobbs_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
