# Generated by Django 5.2.12 on 2026-04-01 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_align_profile_pilot_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscrepancyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated')], default='updated', max_length=32)),
                ('summary', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discrepancy_activities', to=settings.AUTH_USER_MODEL)),
                ('discrepancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.discrepancy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated')], default='updated', max_length=32)),
                ('summary', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_activities', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.workorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
