# Generated by Django 5.2.12 on 2026-04-21 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_workorder_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='aircraft_type',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='fleet_status',
            field=models.CharField(choices=[('active', 'Active'), ('maintenance_due', 'Maintenance Due'), ('aog', 'AOG'), ('grounded', 'Grounded')], default='active', max_length=40),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='hobbs_current',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='specs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='tach_current',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='AircraftMaintenanceInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('interval_type', models.CharField(choices=[('hours', 'Hours'), ('days', 'Days'), ('both', 'Both')], default='hours', max_length=20)),
                ('due_every_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('due_every_days', models.PositiveIntegerField(blank=True, null=True)),
                ('last_done_tach', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('last_done_hobbs', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('last_done_date', models.DateField(blank=True, null=True)),
                ('is_ad', models.BooleanField(default=False)),
                ('ad_number', models.CharField(blank=True, default='', max_length=80)),
                ('ad_revision', models.CharField(blank=True, default='', max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_intervals', to='api.aircraft')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AircraftPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='aircraft_photos/')),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.aircraft')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
