# Generated by Django 5.2.12 on 2026-04-21 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_discrepancy_signature_discrepancy_signature_date_and_more"),
        ("api", "0041_aircraft_aircraft_type_aircraft_fleet_status_and_more"),
    ]

    operations = []
