# Generated by Django 5.2.8 on 2026-04-24 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_tool_calibrationrecord'),
    ]

    operations = []
