# Generated by Django 5.2.8 on 2026-04-24 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_tool_calibrationrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='hobbs_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventory_name',
            field=models.CharField(default='Main', max_length=100),
        ),
        migrations.CreateModel(
            name='AircraftPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('expiration_hobbs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aircraft')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_aircrafts', to='api.part')),
            ],
        ),
        migrations.AddField(
            model_name='aircraft',
            name='aircraft_parts',
            field=models.ManyToManyField(blank=True, related_name='aircrafts', through='api.AircraftPart', to='api.part'),
        ),
    ]
