# Generated by Django 5.2.8 on 2026-04-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_aircraft_hobbs_time_inventory_inventory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderpart',
            name='part_expiration_date',
            field=models.DateField(blank=True, help_text='Date the part expires. Optional, only used if part is tracked by expiration date.', null=True),
        ),
        migrations.AddField(
            model_name='workorderpart',
            name='part_life',
            field=models.PositiveIntegerField(blank=True, help_text='Number of hobbs hours the part is good for. Optional, only used if part is tracked by hobbs time.', null=True),
        ),
    ]
