# Generated by Django 5.2.8 on 2026-05-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_workorderpart_part_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderpart',
            name='part_life',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Number of hobbs hours the part is good for. Optional, only used if part is tracked by hobbs time.', max_digits=15, null=True),
        ),
    ]
