# Generated by Django 5.2.8 on 2026-05-13 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_workorderpart_part_life'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
