# Generated by Django 5.2.8 on 2026-05-18 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_aircraft_hobbs_time'),
        ('api', '0047_aircraft_created_at'),
    ]

    operations = [
    ]
