# Generated by Django 5.2.8 on 2026-05-18 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_merge_20260517_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.aircraft'),
        ),
    ]
