# Generated by Django 5.2.14 on 2026-05-26 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_laborentry'),
        ('api', '0049_alter_part_aircraft'),
    ]

    operations = [
    ]
