# Generated by Django 5.2.7 on 2025-10-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.IntegerField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('year_built', models.IntegerField(max_length=4)),
            ],
        ),
    ]
