# Generated by Django 5.2.7 on 2025-11-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_aviation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='registration_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='worker',
            name='employee_ID',
            field=models.IntegerField(),
        ),
    ]
