# Generated by Django 5.2.7 on 2025-11-04 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_aviation_app', '0002_alter_aircraft_registration_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Aircraft', to='alpha_aviation_app.company'),
        ),
        migrations.AddField(
            model_name='worker',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Workers', to='alpha_aviation_app.company'),
        ),
    ]
