# Generated by Django 5.2.8 on 2025-11-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='companyRole',
            field=models.CharField(choices=[('owner', 'Owner'), ('mechanic', 'Mechanic'), ('pilot', 'Pilot')], default='pilot'),
        ),
    ]
