# Generated by Django 5.2.8 on 2025-11-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_companyrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='companyRole',
            field=models.CharField(choices=[('owner', 'Owner'), ('mechanic', 'Mechanic'), ('pilot', 'Pilot')], default='pilot', max_length=255),
        ),
    ]
