# Generated by Django 5.2.8 on 2025-11-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='companyRole',
            new_name='company_role',
        ),
        migrations.AddField(
            model_name='profile',
            name='pilot_certificate',
            field=models.CharField(choices=[('none', 'None'), ('student', 'Student'), ('private', 'Private'), ('commercial', 'Commercial'), ('airline', 'Airline')], default='None', max_length=255),
        ),
    ]
