# Generated by Django 5.2.8 on 2025-11-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_companyrole_profile_company_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='AP_certificate_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
