# Generated by Django 5.2.8 on 2025-11-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_profile_inspector_authentication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='authentication_img',
            field=models.ImageField(blank=True, null=True, upload_to='faa_auth/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mechanic_certificate_img',
            field=models.ImageField(blank=True, null=True, upload_to='mechanic_cert/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
