# Generated by Django 5.2.8 on 2025-11-18 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_profile_authentication_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='AP_certificate_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='authentication_img',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='inspector_authentication',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mechanic_certificate_img',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='medically_cleared_until',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pilot_certificate',
        ),
        migrations.CreateModel(
            name='mechanic_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AP_certificate_number', models.PositiveIntegerField(blank=True, null=True)),
                ('mechanic_certificate_img', models.ImageField(blank=True, null=True, upload_to='mechanic_cert/')),
                ('inspector_authentication', models.BooleanField(default=False)),
                ('authentication_img', models.ImageField(blank=True, null=True, upload_to='faa_auth/')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pilot_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medically_cleared_until', models.DateField(blank=True, null=True)),
                ('pilot_certificate', models.CharField(choices=[('none', 'None'), ('student', 'Student'), ('private', 'Private'), ('commercial', 'Commercial'), ('airline', 'Airline')], default='None', max_length=255)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
