# Generated by Django 5.2.8 on 2025-12-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_mechanic_info_mechanic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='inspection_due_in',
            field=models.PositiveIntegerField(blank=True, help_text='Days', null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='low_stock',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='shop_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='stock_alert',
            field=models.PositiveIntegerField(default=0, help_text='Number where stock needs to be reordered'),
        ),
    ]
